
package com.wangp.ws.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyService1ImplService", targetNamespace = "http://impl.service.ws.wangp.com/", wsdlLocation = "http://localhost:8908/ws?wsdl")
public class MyService1ImplService
    extends Service
{

    private final static URL MYSERVICE1IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVICE1IMPLSERVICE_EXCEPTION;
    private final static QName MYSERVICE1IMPLSERVICE_QNAME = new QName("http://impl.service.ws.wangp.com/", "MyService1ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8908/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICE1IMPLSERVICE_WSDL_LOCATION = url;
        MYSERVICE1IMPLSERVICE_EXCEPTION = e;
    }

    public MyService1ImplService() {
        super(__getWsdlLocation(), MYSERVICE1IMPLSERVICE_QNAME);
    }

    public MyService1ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICE1IMPLSERVICE_QNAME, features);
    }

    public MyService1ImplService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICE1IMPLSERVICE_QNAME);
    }

    public MyService1ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICE1IMPLSERVICE_QNAME, features);
    }

    public MyService1ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService1ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMyService1
     */
    @WebEndpoint(name = "MyService1ImplPort")
    public IMyService1 getMyService1ImplPort() {
        return super.getPort(new QName("http://impl.service.ws.wangp.com/", "MyService1ImplPort"), IMyService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMyService1
     */
    @WebEndpoint(name = "MyService1ImplPort")
    public IMyService1 getMyService1ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.ws.wangp.com/", "MyService1ImplPort"), IMyService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICE1IMPLSERVICE_EXCEPTION!= null) {
            throw MYSERVICE1IMPLSERVICE_EXCEPTION;
        }
        return MYSERVICE1IMPLSERVICE_WSDL_LOCATION;
    }

}
